<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE document PUBLIC "+//IDN docutils.sourceforge.net//DTD Docutils Generic//EN//XML" "http://docutils.sourceforge.net/docs/ref/docutils.dtd">
<!-- Generated by Docutils 0.13.1 -->
<document source="/home/fbaumanis/openstack/soc8_test/openstack_repo/cinder/doc/source/contributor/api/cinder.volume.drivers.netapp.eseries.exception.rst">
    <section ids="module-cinder.volume.drivers.netapp.eseries.exception the-cinder-volume-drivers-netapp-eseries-exception-module" names="the\ cinder.volume.drivers.netapp.eseries.exception\ module">
        <title>The <reference internal="True" refid="module-cinder.volume.drivers.netapp.eseries.exception" reftitle="cinder.volume.drivers.netapp.eseries.exception"><literal classes="xref py py-mod">cinder.volume.drivers.netapp.eseries.exception</literal></reference> Module</title>
        <index entries="['single',\ 'cinder.volume.drivers.netapp.eseries.exception\ (module)',\ 'module-cinder.volume.drivers.netapp.eseries.exception',\ '',\ None]"></index>
        <index entries="['single',\ 'UnsupportedHostGroup',\ 'cinder.volume.drivers.netapp.eseries.exception.UnsupportedHostGroup',\ '',\ None]"></index>
        <desc desctype="exception" domain="py" noindex="False" objtype="exception">
            <desc_signature class="" first="False" fullname="UnsupportedHostGroup" ids="cinder.volume.drivers.netapp.eseries.exception.UnsupportedHostGroup" module="cinder.volume.drivers.netapp.eseries.exception" names="cinder.volume.drivers.netapp.eseries.exception.UnsupportedHostGroup"><desc_annotation xml:space="preserve">exception </desc_annotation><desc_name xml:space="preserve">UnsupportedHostGroup</desc_name><desc_parameterlist xml:space="preserve"><desc_parameter xml:space="preserve">message=None</desc_parameter><desc_parameter xml:space="preserve">**kwargs</desc_parameter></desc_parameterlist></desc_signature>
            <desc_content>
                <paragraph>Bases: <reference internal="True" reftitle="cinder.exception.NetAppDriverException" refuri="cinder.exception#cinder.exception.NetAppDriverException"><literal classes="xref py py-class">cinder.exception.NetAppDriverException</literal></reference></paragraph>
                <index entries="['single',\ 'message\ (UnsupportedHostGroup\ attribute)',\ 'cinder.volume.drivers.netapp.eseries.exception.UnsupportedHostGroup.message',\ '',\ None]"></index>
                <desc desctype="attribute" domain="py" noindex="False" objtype="attribute">
                    <desc_signature class="UnsupportedHostGroup" first="False" fullname="UnsupportedHostGroup.message" ids="cinder.volume.drivers.netapp.eseries.exception.UnsupportedHostGroup.message" module="cinder.volume.drivers.netapp.eseries.exception" names="cinder.volume.drivers.netapp.eseries.exception.UnsupportedHostGroup.message"><desc_name xml:space="preserve">message</desc_name><desc_annotation xml:space="preserve"> = 'Volume %(volume_id)s is currently mapped to unsupported host group %(group)s'</desc_annotation></desc_signature>
                    <desc_content>
                    </desc_content>
                </desc>
            </desc_content>
        </desc>
        <index entries="['single',\ 'VolumeNotMapped',\ 'cinder.volume.drivers.netapp.eseries.exception.VolumeNotMapped',\ '',\ None]"></index>
        <desc desctype="exception" domain="py" noindex="False" objtype="exception">
            <desc_signature class="" first="False" fullname="VolumeNotMapped" ids="cinder.volume.drivers.netapp.eseries.exception.VolumeNotMapped" module="cinder.volume.drivers.netapp.eseries.exception" names="cinder.volume.drivers.netapp.eseries.exception.VolumeNotMapped"><desc_annotation xml:space="preserve">exception </desc_annotation><desc_name xml:space="preserve">VolumeNotMapped</desc_name><desc_parameterlist xml:space="preserve"><desc_parameter xml:space="preserve">message=None</desc_parameter><desc_parameter xml:space="preserve">**kwargs</desc_parameter></desc_parameterlist></desc_signature>
            <desc_content>
                <paragraph>Bases: <reference internal="True" reftitle="cinder.exception.NetAppDriverException" refuri="cinder.exception#cinder.exception.NetAppDriverException"><literal classes="xref py py-class">cinder.exception.NetAppDriverException</literal></reference></paragraph>
                <index entries="['single',\ 'message\ (VolumeNotMapped\ attribute)',\ 'cinder.volume.drivers.netapp.eseries.exception.VolumeNotMapped.message',\ '',\ None]"></index>
                <desc desctype="attribute" domain="py" noindex="False" objtype="attribute">
                    <desc_signature class="VolumeNotMapped" first="False" fullname="VolumeNotMapped.message" ids="cinder.volume.drivers.netapp.eseries.exception.VolumeNotMapped.message" module="cinder.volume.drivers.netapp.eseries.exception" names="cinder.volume.drivers.netapp.eseries.exception.VolumeNotMapped.message"><desc_name xml:space="preserve">message</desc_name><desc_annotation xml:space="preserve"> = 'Volume %(volume_id)s is not currently mapped to host %(host)s'</desc_annotation></desc_signature>
                    <desc_content>
                    </desc_content>
                </desc>
            </desc_content>
        </desc>
        <index entries="['single',\ 'WebServiceException',\ 'cinder.volume.drivers.netapp.eseries.exception.WebServiceException',\ '',\ None]"></index>
        <desc desctype="exception" domain="py" noindex="False" objtype="exception">
            <desc_signature class="" first="False" fullname="WebServiceException" ids="cinder.volume.drivers.netapp.eseries.exception.WebServiceException" module="cinder.volume.drivers.netapp.eseries.exception" names="cinder.volume.drivers.netapp.eseries.exception.WebServiceException"><desc_annotation xml:space="preserve">exception </desc_annotation><desc_name xml:space="preserve">WebServiceException</desc_name><desc_parameterlist xml:space="preserve"><desc_parameter xml:space="preserve">message=None</desc_parameter><desc_parameter xml:space="preserve">status_code=None</desc_parameter></desc_parameterlist></desc_signature>
            <desc_content>
                <paragraph>Bases: <reference internal="True" reftitle="cinder.exception.NetAppDriverException" refuri="cinder.exception#cinder.exception.NetAppDriverException"><literal classes="xref py py-class">cinder.exception.NetAppDriverException</literal></reference></paragraph>
            </desc_content>
        </desc>
    </section>
</document>
